-- Insert Dominican Republic provinces
INSERT INTO provinces (name, code) VALUES
('Azua', 'AZ'),
('Baoruco', 'BO'),
('Barahona', 'BH'),
('Dajabón', 'DJ'),
('Distrito Nacional', 'DN'),
('Duarte', 'DU'),
('El Seibo', 'ES'),
('Elías Piña', 'EP'),
('Espaillat', 'ET'),
('Hato Mayor', 'HM'),
('Hermanas Mirabal', 'HI'),
('Independencia', 'IN'),
('La Altagracia', 'AL'),
('La Romana', 'RO'),
('La Vega', 'VE'),
('María Trinidad Sánchez', 'MT'),
('Monseñor Nouel', 'MN'),
('Monte Cristi', 'MC'),
('Monte Plata', 'MP'),
('Pedernales', 'PE'),
('Peravia', 'PR'),
('Puerto Plata', 'PP'),
('Samaná', 'SM'),
('San Cristóbal', 'SC'),
('San José de Ocoa', 'JO'),
('San Juan', 'SJ'),
('San Pedro de Macorís', 'MA'),
('Sánchez Ramírez', 'SR'),
('Santiago', 'ST'),
('Santiago Rodríguez', 'SL'),
('Santo Domingo', 'SD'),
('Valverde', 'VV')
-- Note: Duplicate check not needed if table is empty